### PR TITLE
update med

### PR DESCRIPTION
**Pull request by adrianinsaval**

### CODE REVIEW

**Comment by adrianinsaval** [comment]
@hfiguiere this build succeeded but flatpak search org.freecad.FreeCAD still comes up with nothing, do I need to do anything else to get it published?

**Comment by hfiguiere** [comment]
> @hfiguiere this build succeeded but flatpak search org.freecad.FreeCAD still comes up with nothing, do I need to do anything else to get it published?

because flathub beta is a different repo. flatpak search likely default to flathub.

**Comment by hfiguiere** [comment]
```
% flatpak search org.freecad.FreeCAD
Name             Description                                       Application ID              Version             Branch         Remotes
FreeCAD          An open source parametric 3D CAD modeler          org.freecad.FreeCAD         1.0.0.38804         beta           flathub-beta
```

**Comment by adrianinsaval** [comment]
huh that's curious, I have both flathub and flathub-beta repos enabled and when searching for org.freecadweb.FreeCAD they both show up. When directly asking to install org.freecad.FreeCAD it finds it in flathub-beta though

**Pull request merged**
